// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9El9skThdKMGEQxd961CfWziCMQ-Dduw',
    appId: '1:340678487127:web:252a4aa33be7e7f85fc712',
    messagingSenderId: '340678487127',
    projectId: 'egg-plant-disease-control',
    authDomain: 'egg-plant-disease-control.firebaseapp.com',
    storageBucket: 'egg-plant-disease-control.appspot.com',
    measurementId: 'G-TZGQFRC4HH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT0jiRw4nBTIh5QDoCalUSstWs3GSF9Jk',
    appId: '1:340678487127:android:16feece1a3749bda5fc712',
    messagingSenderId: '340678487127',
    projectId: 'egg-plant-disease-control',
    storageBucket: 'egg-plant-disease-control.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByirPM2UFtTqcRQAjdCOcqdWc-l_ll4Lw',
    appId: '1:340678487127:ios:ffe32e3c21c1af6f5fc712',
    messagingSenderId: '340678487127',
    projectId: 'egg-plant-disease-control',
    storageBucket: 'egg-plant-disease-control.appspot.com',
    iosBundleId: 'com.example.susya',
  );
}
